### ISSUE TITLE
PythonCall `v0.9.9` cannot be loaded

### ISSUE THREAD

**Issue by thazhemadam** [cjdoris/PythonCall.jl#241] opened 2022-11-02 07:33 UTC
# Description

Trying to load the `PythonCall` package fails due to an artifact hash mismatch error.

# MWE
```julia
using Pkg
Pkg.add("PythonCall")
using PythonCall
```

# Stacktrace
```julia
julia> using PythonCall
    CondaPkg Found dependencies: /home/thazhemadam/.julia/packages/PythonCall/Td3SH/CondaPkg.toml
    CondaPkg Resolving changes
             + libstdcxx-ng
             + python
  Downloaded artifact: micromamba-0.27.0
 Downloading artifact: micromamba-0.27.0
┌ Error: Hash Mismatch!
│   Expected sha256:   4adbf3091a4159af2c48264a8e32ecb98147b0e3f200601f384f8f53a6910ca2
│   Calculated sha256: 1bb0c8896927a64a6d73a33fa08a915c22c57b240db92e2d6595b6741f509ed0
  Downloaded artifact: micromamba-0.27.0
ERROR: InitError: Unable to automatically install 'micromamba-0.27.0' from '/home/thazhemadam/.julia/packages/MicroMamba/rCGZ4/Artifacts.toml'
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] ensure_artifact_installed(name::String, meta::Dict{String, Any}, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool, io::Base.TTY)
    @ Pkg.Artifacts ~/.julia/juliaup/julia-1.7.3+0.x64/share/julia/stdlib/v1.7/Pkg/src/Artifacts.jl:441
  [3] ensure_artifact_installed(name::String, artifacts_toml::String; platform::Base.BinaryPlatforms.Platform, pkg_uuid::Nothing, verbose::Bool, quiet_download::Bool, io::Base.TTY)
    @ Pkg.Artifacts ~/.julia/juliaup/julia-1.7.3+0.x64/share/julia/stdlib/v1.7/Pkg/src/Artifacts.jl:404
  [4] executable(; io::IO)
    @ MicroMamba ~/.julia/packages/MicroMamba/rCGZ4/src/MicroMamba.jl:37
  [5] cmd(; io::IO)
    @ MicroMamba ~/.julia/packages/MicroMamba/rCGZ4/src/MicroMamba.jl:115
  [6] cmd(args::Any; io::IO)
    @ MicroMamba ~/.julia/packages/MicroMamba/rCGZ4/src/MicroMamba.jl:119
  [7] conda_cmd(args::Any; io::IO)
    @ CondaPkg ~/.julia/packages/CondaPkg/RuSdR/src/backend.jl:40
  [8] _resolve_conda_install(io::Any, conda_env::Any, specs::Any, channels::Any; create::Any)
    @ CondaPkg ~/.julia/packages/CondaPkg/RuSdR/src/resolve.jl:200
  [9] resolve(; force::Bool, io::IO, interactive::Bool, dry_run::Bool)
    @ CondaPkg ~/.julia/packages/CondaPkg/RuSdR/src/resolve.jl:452
 [10] resolve()
    @ CondaPkg ~/.julia/packages/CondaPkg/RuSdR/src/resolve.jl:317
 [11] envdir()
    @ CondaPkg ~/.julia/packages/CondaPkg/RuSdR/src/env.jl:70
 [12] init_context()
    @ PythonCall.C ~/.julia/packages/PythonCall/Td3SH/src/cpython/context.jl:83
 [13] __init__()
    @ PythonCall.C ~/.julia/packages/PythonCall/Td3SH/src/cpython/CPython.jl:21
 [14] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
 [15] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
 [16] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
 [17] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
 [18] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
during initialization of module C
```

**Comment by hhaensel** [comment] 2022-11-02 10:31
Duplicate of #238

**Comment by cjdoris** [comment] 2022-11-17 13:56
Should be fixed.

**Closed by cjdoris** 2022-11-17 13:56 UTC
