### ISSUE TITLE
"Python exited unexpectedly" when using external conda environment

### ISSUE THREAD

**Issue by charstnut** [cjdoris/PythonCall.jl#85] opened 2021-12-14 21:11 UTC
Thank you for this great package!

I've come across this warning after configuring PythonCall to use the PyCall environment. It does not seem to interfere with usage though. When using "Ctrl + D" for exit this results in segmentation fault but still exits.

MWE after starting julia:
```
julia > ENV["JULIA_PYTHONCALL_EXE"] = "@PyCall"
julia > using PythonCall
julia> exit()
┌ Warning: Python exited unexpectedly
└ @ PythonCall.C ~/.julia/packages/PythonCall/zJpsh/src/cpython/context.jl:179
```

**Comment by cjdoris** [comment] 2021-12-15 09:20
Thanks. The issue is that both PythonCall and PyCall act like they "own" the Python interpreter instance, which is a bug.

I'm rewriting the initialisation part of PythonCall soon so I'll make sure this bug is fixed as part of that.

**Comment by cjdoris** [comment] 2021-12-16 17:22
I believe this is fixed now on the master branch. Can you check please?

**Comment by charstnut** [comment] 2021-12-16 18:50
Thanks! I just pulled and it works! No more errors. 

Just a note, it is probably necessary to run `Pkg.resolve()` inside the `julia_env` folder in the custom conda environment after reinstalling the python package if the dependencies change.

**Comment by charstnut** [comment] 2021-12-16 19:03
I checked from the python side and it works without any problem.

(Just a note, it is probably necessary to run Pkg.resolve() inside the julia_env folder in the custom conda environment after reinstalling the python package if the dependencies change.)

For the julia side, it still exits with this warning. I assume updating the package using `Pkg.up()` would be sufficient?

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0 (2021-11-30)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using PythonCall

julia> exit()
┌ Warning: Python exited unexpectedly
└ @ PythonCall.C ~/.julia/packages/PythonCall/zJpsh/src/cpython/context.jl:179
```

**Comment by cjdoris** [comment] 2021-12-16 19:16
Aha I missed a case, I can make that warning go away. Thanks for checking.

Yeah the resolve thing you mentioned only affects people running the development version.

**Comment by cjdoris** [comment] 2022-01-07 18:28
Pretty sure this is correct on `main` now. Let me know if not.

**Closed by cjdoris** 2022-01-07 18:28 UTC
Labels: bug, priority

**Comment by charstnut** [comment] 2022-01-07 23:21
Thanks! Confirmed this is fixed.
