### ISSUE TITLE
Display for `pytype` in Pluto notebooks

### ISSUE THREAD

**Issue by icweaver** [cjdoris/PythonCall.jl#101] opened 2022-01-24 18:20 UTC
`pytype` seems to throw the following for me in a Pluto notebook:

```julia
using PythonCall

x_py = pylist([1, 2, 3])
# x_py = Python list: [1, 2, 3]

pytype(x_py)
```

```
Failed to show value:

MethodError: no method matching show(::IOContext{IOBuffer}, ::Nothing, ::PythonCall.Py)

Closest candidates are:

show(::IO, !Matched::AbstractString, ::Any) at ~/julia-1.7.1/share/julia/base/multimedia.jl:111
show(::IO, !Matched::MIME{Symbol("text/csv")}, ::PythonCall.Py) at ~/.julia/packages/PythonCall/59kNC/src/Py.jl:266
show(::IO, !Matched::MIME{Symbol("text/csv")}, ::Any) at ~/julia-1.7.1/share/julia/stdlib/v1.7/DelimitedFiles/src/DelimitedFiles.jl:829
...
    1. show_richest(::IOContext{IOBuffer}, ::Any)@PlutoRunner.jl:1019
    2. var"#sprint_withreturned#54"(::IOContext{Base.DevNull}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::PythonCall.Py)@PlutoRunner.jl:954
    3. format_output_default(::Any, ::Any)@PlutoRunner.jl:862
    4. var"#format_output#42"(::IOContext{Base.DevNull}, ::typeof(Main.PlutoRunner.format_output), ::Any)@PlutoRunner.jl:879
    5. formatted_result_of(::Base.UUID, ::Bool, ::Vector{String}, ::Nothing, ::Module)@PlutoRunner.jl:785
    6. top-level scope@none:1
```

while printing to plain text looks to work fine I think:

```julia
println(pytype(x_py)) # <class 'list'>
```

albeit the display is slightly different than just running it directly in the REPL:

```bash
julia> using PythonCall
    
julia> x_py = pylist([1, 2, 3])
Python list: [1, 2, 3]

julia> pytype(x_py)
Python type: <class 'list'>
```

Loving all the new updates by the way!

**Comment by cjdoris** [comment] 2022-01-24 18:57
Thanks! It's a bug caused by the fact that `x.__repr__()` doesn't work when `x` is a `type`, you need to do `type(x).__repr__(x)` instead. Fixed on main branch.

**Closed by cjdoris** 2022-01-24 18:57 UTC

**Comment by icweaver** [comment] 2022-01-24 19:02
Wow, you are insanely fast

![dog-race](https://user-images.githubusercontent.com/25312320/150847062-343e81b1-4b15-4e02-9434-29a95f0774d4.gif)

Thanks so much for the quick fix, it works beautifully!

**Comment by cjdoris** [comment] 2022-01-24 19:10
Haha, you were just lucky to catch me while I was already looking at PythonCall!
